"""Mako template for generating migration scripts."""

"""add_demand_strategy_config_keys

Revision ID: 6b35deb365c7
Revises: 003_add_alerts
Create Date: 2026-04-14 15:42:23.763225+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b35deb365c7'
down_revision = '003_add_alerts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_created_at_desc', table_name='alerts')
    op.create_index('idx_alerts_created_at_desc', 'alerts', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_runs_id'), 'analytics_runs', ['id'], unique=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.drop_index('idx_audit_created_at_desc', table_name='audit_logs')
    op.create_index('idx_audit_created_at_desc', 'audit_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_hedge_positions_id'), 'hedge_positions', ['id'], unique=False)
    op.create_index(op.f('ix_hedge_recommendations_id'), 'hedge_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_platform_config_id'), 'platform_config', ['id'], unique=False)
    op.drop_index('idx_price_ticks_time_desc', table_name='price_ticks')
    op.create_index('idx_price_ticks_time_desc', 'price_ticks', ['time'], unique=False, postgresql_ops={'time': 'DESC'})
    op.create_index(op.f('ix_price_ticks_id'), 'price_ticks', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_price_ticks_id'), table_name='price_ticks')
    op.drop_index('idx_price_ticks_time_desc', table_name='price_ticks', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_price_ticks_time_desc', 'price_ticks', [sa.text('time DESC')], unique=False)
    op.drop_index(op.f('ix_platform_config_id'), table_name='platform_config')
    op.drop_index(op.f('ix_hedge_recommendations_id'), table_name='hedge_recommendations')
    op.drop_index(op.f('ix_hedge_positions_id'), table_name='hedge_positions')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_created_at_desc', table_name='audit_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_audit_created_at_desc', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_index(op.f('ix_analytics_runs_id'), table_name='analytics_runs')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index('idx_alerts_created_at_desc', table_name='alerts', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_alerts_created_at_desc', 'alerts', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
